In [1]:
# ================== Notebook Setup ==================
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
from __future__ import annotations

from pathlib import Path
import pandas as pd
import numpy as np

In [3]:
# ================== Setup Directory Structure ==================
NB_DIR = Path.cwd()
PROJECT_ROOT = NB_DIR

# Data directories
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"

# Artifact directories
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
AUDIT_DIR = ARTIFACTS_DIR / "audit"
MODELS_DIR = ARTIFACTS_DIR / "models"
PLOTS_DIR = ARTIFACTS_DIR / "plots"
REPORTS_DIR = ARTIFACTS_DIR / "reports"
TABLES_DIR = ARTIFACTS_DIR / "tables"

# Raw file
RAW_DATA_PATH = RAW_DIR / "CompaniesHouseData-2026-03-02.csv"

# Create directories
for folder in [
    DATA_DIR,
    RAW_DIR,
    PROCESSED_DIR,
    ARTIFACTS_DIR,
    AUDIT_DIR,
    TABLES_DIR,
    PLOTS_DIR,
    REPORTS_DIR,
    MODELS_DIR,
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw data path:", RAW_DATA_PATH)

Project root: /Users/lingzitong/Desktop/MSIN0166 Individual Assignment
Raw data path: /Users/lingzitong/Desktop/MSIN0166 Individual Assignment/data/raw/CompaniesHouseData-2026-03-02.csv

In [4]:
# Upload the original data set
raw_data = pd.read_csv(RAW_DATA_PATH, encoding="utf-8")
print(raw_data.shape)

/var/folders/2j/pl598g1j2xz2pdz1zs5r31vr0000gn/T/ipykernel_12207/1484453964.py:2: DtypeWarning: Columns (3,41,42,43,44,45,46,47,48,49,50,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv(RAW_DATA_PATH, encoding="utf-8")

(5677276, 55)

In [5]:
raw_data.columns.tolist()

['CompanyName',
 ' CompanyNumber',
 'RegAddress.CareOf',
 'RegAddress.POBox',
 'RegAddress.AddressLine1',
 ' RegAddress.AddressLine2',
 'RegAddress.PostTown',
 'RegAddress.County',
 'RegAddress.Country',
 'RegAddress.PostCode',
 'CompanyCategory',
 'CompanyStatus',
 'CountryOfOrigin',
 'DissolutionDate',
 'IncorporationDate',
 'Accounts.AccountRefDay',
 'Accounts.AccountRefMonth',
 'Accounts.NextDueDate',
 'Accounts.LastMadeUpDate',
 'Accounts.AccountCategory',
 'Returns.NextDueDate',
 'Returns.LastMadeUpDate',
 'Mortgages.NumMortCharges',
 'Mortgages.NumMortOutstanding',
 'Mortgages.NumMortPartSatisfied',
 'Mortgages.NumMortSatisfied',
 'SICCode.SicText_1',
 'SICCode.SicText_2',
 'SICCode.SicText_3',
 'SICCode.SicText_4',
 'LimitedPartnerships.NumGenPartners',
 'LimitedPartnerships.NumLimPartners',
 'URI',
 'PreviousName_1.CONDATE',
 ' PreviousName_1.CompanyName',
 ' PreviousName_2.CONDATE',
 ' PreviousName_2.CompanyName',
 'PreviousName_3.CONDATE',
 ' PreviousName_3.CompanyName',
 'PreviousName_4.CONDATE',
 ' PreviousName_4.CompanyName',
 'PreviousName_5.CONDATE',
 ' PreviousName_5.CompanyName',
 'PreviousName_6.CONDATE',
 ' PreviousName_6.CompanyName',
 'PreviousName_7.CONDATE',
 ' PreviousName_7.CompanyName',
 'PreviousName_8.CONDATE',
 ' PreviousName_8.CompanyName',
 'PreviousName_9.CONDATE',
 ' PreviousName_9.CompanyName',
 'PreviousName_10.CONDATE',
 ' PreviousName_10.CompanyName',
 'ConfStmtNextDueDate',
 ' ConfStmtLastMadeUpDate']

In [6]:
# Clean raw column names
raw_data.columns = (
    raw_data.columns
    .str.strip()
)

raw_data.columns.tolist()

['CompanyName',
 'CompanyNumber',
 'RegAddress.CareOf',
 'RegAddress.POBox',
 'RegAddress.AddressLine1',
 'RegAddress.AddressLine2',
 'RegAddress.PostTown',
 'RegAddress.County',
 'RegAddress.Country',
 'RegAddress.PostCode',
 'CompanyCategory',
 'CompanyStatus',
 'CountryOfOrigin',
 'DissolutionDate',
 'IncorporationDate',
 'Accounts.AccountRefDay',
 'Accounts.AccountRefMonth',
 'Accounts.NextDueDate',
 'Accounts.LastMadeUpDate',
 'Accounts.AccountCategory',
 'Returns.NextDueDate',
 'Returns.LastMadeUpDate',
 'Mortgages.NumMortCharges',
 'Mortgages.NumMortOutstanding',
 'Mortgages.NumMortPartSatisfied',
 'Mortgages.NumMortSatisfied',
 'SICCode.SicText_1',
 'SICCode.SicText_2',
 'SICCode.SicText_3',
 'SICCode.SicText_4',
 'LimitedPartnerships.NumGenPartners',
 'LimitedPartnerships.NumLimPartners',
 'URI',
 'PreviousName_1.CONDATE',
 'PreviousName_1.CompanyName',
 'PreviousName_2.CONDATE',
 'PreviousName_2.CompanyName',
 'PreviousName_3.CONDATE',
 'PreviousName_3.CompanyName',
 'PreviousName_4.CONDATE',
 'PreviousName_4.CompanyName',
 'PreviousName_5.CONDATE',
 'PreviousName_5.CompanyName',
 'PreviousName_6.CONDATE',
 'PreviousName_6.CompanyName',
 'PreviousName_7.CONDATE',
 'PreviousName_7.CompanyName',
 'PreviousName_8.CONDATE',
 'PreviousName_8.CompanyName',
 'PreviousName_9.CONDATE',
 'PreviousName_9.CompanyName',
 'PreviousName_10.CONDATE',
 'PreviousName_10.CompanyName',
 'ConfStmtNextDueDate',
 'ConfStmtLastMadeUpDate']

In [7]:
expected_columns = [
    "CompanyNumber",
    "CompanyName",
    "CompanyCategory",
    "CompanyStatus",
    "CountryOfOrigin",
    "IncorporationDate",
    "Accounts.AccountCategory",
    "SICCode.SicText_1",
    "SICCode.SicText_2",
    "SICCode.SicText_3",
    "SICCode.SicText_4",
    "RegAddress.PostTown",
    "RegAddress.County",
    "RegAddress.Country",
    "RegAddress.PostCode",
    "URI",
]

missing_expected = [column for column in expected_columns if column not in raw_data.columns]
present_expected = [column for column in expected_columns if column in raw_data.columns]

print("Present expected columns:", present_expected)
print("Missing expected columns:", missing_expected)

Present expected columns: ['CompanyNumber', 'CompanyName', 'CompanyCategory', 'CompanyStatus', 'CountryOfOrigin', 'IncorporationDate', 'Accounts.AccountCategory', 'SICCode.SicText_1', 'SICCode.SicText_2', 'SICCode.SicText_3', 'SICCode.SicText_4', 'RegAddress.PostTown', 'RegAddress.County', 'RegAddress.Country', 'RegAddress.PostCode', 'URI']
Missing expected columns: []

In [8]:
entity_master = raw_data[expected_columns].copy()
print(entity_master.shape)
entity_master.head()

(5677276, 16)

,CompanyNumber,CompanyName,CompanyCategory,CompanyStatus,CountryOfOrigin,IncorporationDate,Accounts.AccountCategory,SICCode.SicText_1,SICCode.SicText_2,SICCode.SicText_3,SICCode.SicText_4,RegAddress.PostTown,RegAddress.County,RegAddress.Country,RegAddress.PostCode,URI
0,08209948,! LTD,Private Limited Company,Active,United Kingdom,11/09/2012,DORMANT,99999 - Dormant Company,NaN,NaN,NaN,HARROGATE,NaN,ENGLAND,HG1 1ND,http://business.data.gov.uk/id/company/08209948
1,11743365,!BIG IMPACT GRAPHICS LIMITED,Private Limited Company,Active,United Kingdom,28/12/2018,DORMANT,59112 - Video production activities,63120 - Web portals,74100 - specialised design activities,74201 - Portrait photographic activities,LONDON,NaN,NaN,EC1V 2NX,http://business.data.gov.uk/id/company/11743365
2,16873705,!FE NETWORK LIMITED,Private Limited Company,Active,United Kingdom,25/11/2025,NO ACCOUNTS FILED,86210 - General medical practice activities,NaN,NaN,NaN,"HARLOW, ESSEX",NaN,UNITED KINGDOM,CM20 1YS,http://business.data.gov.uk/id/company/16873705
3,15073164,!NFLECTION ADVISORY LIMITED,Private Limited Company,Active,United Kingdom,15/08/2023,TOTAL EXEMPTION FULL,70229 - Management consultancy activities othe...,NaN,NaN,NaN,POTTERS BAR,HERTFORDSHIRE,ENGLAND,EN6 2DA,http://business.data.gov.uk/id/company/15073164
4,13522064,!NFOGENIE LTD,Private Limited Company,Active,United Kingdom,21/07/2021,MICRO ENTITY,58290 - Other software publishing,NaN,NaN,NaN,LONDON,GREATER LONDON,UNITED KINGDOM,WC2H 9JQ,http://business.data.gov.uk/id/company/13522064

In [9]:
rename_map = {
    "CompanyNumber": "entity_id",
    "CompanyName": "entity_name",
    "CompanyCategory": "company_category",
    "CompanyStatus": "company_status",
    "CountryOfOrigin": "country_of_origin",
    "IncorporationDate": "incorporation_date",
    "Accounts.AccountCategory": "account_category",
    "SICCode.SicText_1": "sic_text_1",
    "SICCode.SicText_2": "sic_text_2",
    "SICCode.SicText_3": "sic_text_3",
    "SICCode.SicText_4": "sic_text_4",
    "RegAddress.PostTown": "post_town",
    "RegAddress.County": "county",
    "RegAddress.Country": "country",
    "RegAddress.PostCode": "postcode",
    "URI": "source_uri",
}

entity_master = entity_master.rename(columns=rename_map)
entity_master.head()

,entity_id,entity_name,company_category,company_status,country_of_origin,incorporation_date,account_category,sic_text_1,sic_text_2,sic_text_3,sic_text_4,post_town,county,country,postcode,source_uri
0,08209948,! LTD,Private Limited Company,Active,United Kingdom,11/09/2012,DORMANT,99999 - Dormant Company,NaN,NaN,NaN,HARROGATE,NaN,ENGLAND,HG1 1ND,http://business.data.gov.uk/id/company/08209948
1,11743365,!BIG IMPACT GRAPHICS LIMITED,Private Limited Company,Active,United Kingdom,28/12/2018,DORMANT,59112 - Video production activities,63120 - Web portals,74100 - specialised design activities,74201 - Portrait photographic activities,LONDON,NaN,NaN,EC1V 2NX,http://business.data.gov.uk/id/company/11743365
2,16873705,!FE NETWORK LIMITED,Private Limited Company,Active,United Kingdom,25/11/2025,NO ACCOUNTS FILED,86210 - General medical practice activities,NaN,NaN,NaN,"HARLOW, ESSEX",NaN,UNITED KINGDOM,CM20 1YS,http://business.data.gov.uk/id/company/16873705
3,15073164,!NFLECTION ADVISORY LIMITED,Private Limited Company,Active,United Kingdom,15/08/2023,TOTAL EXEMPTION FULL,70229 - Management consultancy activities othe...,NaN,NaN,NaN,POTTERS BAR,HERTFORDSHIRE,ENGLAND,EN6 2DA,http://business.data.gov.uk/id/company/15073164
4,13522064,!NFOGENIE LTD,Private Limited Company,Active,United Kingdom,21/07/2021,MICRO ENTITY,58290 - Other software publishing,NaN,NaN,NaN,LONDON,GREATER LONDON,UNITED KINGDOM,WC2H 9JQ,http://business.data.gov.uk/id/company/13522064

In [10]:
entity_master["entity_name"].str.startswith("!").value_counts(dropna=False)

entity_name
False    5677265
True          11
Name: count, dtype: int64

In [11]:
entity_master.loc[
    entity_master["entity_name"].str.startswith("!", na=False),
    ["entity_id", "entity_name", "company_status", "company_category"]
]

,entity_id,entity_name,company_status,company_category
0,08209948,! LTD,Active,Private Limited Company
1,11743365,!BIG IMPACT GRAPHICS LIMITED,Active,Private Limited Company
2,16873705,!FE NETWORK LIMITED,Active,Private Limited Company
3,15073164,!NFLECTION ADVISORY LIMITED,Active,Private Limited Company
4,13522064,!NFOGENIE LTD,Active,Private Limited Company
5,11006939,!NNOV8 LIMITED,Active,Private Limited Company
6,SC606050,!NSPIRED INVESTMENTS LTD,Active,Private Limited Company
7,SC421617,!NSPIRED LTD,Liquidation,Private Limited Company
8,FC031362,!OBAC LIMITED,Active,Other company type
9,07687209,!OBAC UK LIMITED,Active,Private Limited Company
10,02714021,!YOZO FASS LIMITED,Active - Proposal to Strike off,Private Limited Company

In [12]:
entity_master["entity_name_raw"] = entity_master["entity_name"]

entity_master["entity_name"] = (
    entity_master["entity_name"]
    .str.replace(r"^!+", "", regex=True)
    .str.strip()
)

entity_master.loc[
    entity_master["entity_name_raw"].str.startswith("!", na=False),
    ["entity_id", "entity_name_raw", "entity_name"]
]

   entity_id               entity_name_raw                  entity_name
0   08209948                         ! LTD                          LTD
1   11743365  !BIG IMPACT GRAPHICS LIMITED  BIG IMPACT GRAPHICS LIMITED
2   16873705           !FE NETWORK LIMITED           FE NETWORK LIMITED
3   15073164   !NFLECTION ADVISORY LIMITED   NFLECTION ADVISORY LIMITED
4   13522064                 !NFOGENIE LTD                 NFOGENIE LTD
5   11006939                !NNOV8 LIMITED                NNOV8 LIMITED
6   SC606050      !NSPIRED INVESTMENTS LTD      NSPIRED INVESTMENTS LTD
7   SC421617                  !NSPIRED LTD                  NSPIRED LTD
8   FC031362                 !OBAC LIMITED                 OBAC LIMITED
9   07687209              !OBAC UK LIMITED              OBAC UK LIMITED
10  02714021            !YOZO FASS LIMITED            YOZO FASS LIMITED

In [13]:
# Move duplicate rows
entity_master = entity_master.drop_duplicates()

# Parse date column
entity_master["incorporation_date"] = pd.to_datetime(
    entity_master["incorporation_date"],
    format="%d/%m/%Y",
    errors="coerce"
)

# Standardise string columns
string_columns = entity_master.select_dtypes(include="object").columns
for column in string_columns:
    entity_master[column] = entity_master[column].str.strip()

# Replace empty strings with NaN
entity_master = entity_master.replace(r"^\s*$", np.nan, regex=True)

print(entity_master.shape)
entity_master.head()

(5677276, 17)

,entity_id,entity_name,company_category,company_status,country_of_origin,incorporation_date,account_category,sic_text_1,sic_text_2,sic_text_3,sic_text_4,post_town,county,country,postcode,source_uri,entity_name_raw
0,08209948,LTD,Private Limited Company,Active,United Kingdom,2012-09-11,DORMANT,99999 - Dormant Company,NaN,NaN,NaN,HARROGATE,NaN,ENGLAND,HG1 1ND,http://business.data.gov.uk/id/company/08209948,! LTD
1,11743365,BIG IMPACT GRAPHICS LIMITED,Private Limited Company,Active,United Kingdom,2018-12-28,DORMANT,59112 - Video production activities,63120 - Web portals,74100 - specialised design activities,74201 - Portrait photographic activities,LONDON,NaN,NaN,EC1V 2NX,http://business.data.gov.uk/id/company/11743365,!BIG IMPACT GRAPHICS LIMITED
2,16873705,FE NETWORK LIMITED,Private Limited Company,Active,United Kingdom,2025-11-25,NO ACCOUNTS FILED,86210 - General medical practice activities,NaN,NaN,NaN,"HARLOW, ESSEX",NaN,UNITED KINGDOM,CM20 1YS,http://business.data.gov.uk/id/company/16873705,!FE NETWORK LIMITED
3,15073164,NFLECTION ADVISORY LIMITED,Private Limited Company,Active,United Kingdom,2023-08-15,TOTAL EXEMPTION FULL,70229 - Management consultancy activities othe...,NaN,NaN,NaN,POTTERS BAR,HERTFORDSHIRE,ENGLAND,EN6 2DA,http://business.data.gov.uk/id/company/15073164,!NFLECTION ADVISORY LIMITED
4,13522064,NFOGENIE LTD,Private Limited Company,Active,United Kingdom,2021-07-21,MICRO ENTITY,58290 - Other software publishing,NaN,NaN,NaN,LONDON,GREATER LONDON,UNITED KINGDOM,WC2H 9JQ,http://business.data.gov.uk/id/company/13522064,!NFOGENIE LTD

In [14]:
missing_summary = (
    entity_master
    .isna()
    .mean()
    .sort_values(ascending=False)
    .rename("missing_ratio")
    .to_frame()
)

missing_summary

                    missing_ratio
sic_text_4               0.960615
sic_text_3               0.914457
sic_text_2               0.802930
county                   0.707691
country                  0.167337
post_town                0.016539
postcode                 0.015778
country_of_origin        0.000051
incorporation_date       0.000005
source_uri               0.000000
entity_id                0.000000
entity_name              0.000000
sic_text_1               0.000000
account_category         0.000000
company_status           0.000000
company_category         0.000000
entity_name_raw          0.000000

In [15]:
entity_master["company_status"].value_counts(dropna=False).head(20)

company_status
Active                                              5156695
Active - Proposal to Strike off                      405506
Liquidation                                          108183
In Administration                                      3445
Live but Receiver Manager on at least one charge       2102
Voluntary Arrangement                                   545
In Administration/Administrative Receiver               332
RECEIVERSHIP                                            181
ADMINISTRATION ORDER                                    122
ADMINISTRATIVE RECEIVER                                 106
In Administration/Receiver Manager                       47
RECEIVER MANAGER / ADMINISTRATIVE RECEIVER               10
VOLUNTARY ARRANGEMENT / RECEIVER MANAGER                  1
VOLUNTARY ARRANGEMENT / ADMINISTRATIVE RECEIVER           1
Name: count, dtype: int64

In [16]:
entity_master["company_category"].value_counts(dropna=False).head(20)

company_category
Private Limited Company                                                                      5252185
PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)                         119735
Limited Partnership                                                                            60519
Limited Liability Partnership                                                                  51280
Community Interest Company                                                                     42144
Charitable Incorporated Organisation                                                           39012
PRI/LBG/NSC (Private, Limited by guarantee, no share capital, use of 'Limited' exemption)      36825
Overseas Entity                                                                                30222
Other company type                                                                             15405
Registered Society                                                                             10691
Scottish Charitable Incorporated Organisation                                                   7501
Public Limited Company                                                                          4681
Private Unlimited Company                                                                       4635
Royal Charter Company                                                                            908
Investment Company with Variable Capital                                                         634
United Kingdom Economic Interest Grouping                                                        263
Scottish Partnership                                                                             251
Industrial and Provident Society                                                                 159
Private Unlimited                                                                                 90
Investment Company with Variable Capital(Umbrella)                                                68
Name: count, dtype: int64

In [17]:
entity_master["account_category"].value_counts(dropna=False).head(20)

account_category
MICRO ENTITY                   1829929
NO ACCOUNTS FILED              1443992
TOTAL EXEMPTION FULL           1330755
DORMANT                         669413
UNAUDITED ABRIDGED              165051
FULL                             87552
SMALL                            69020
AUDIT EXEMPTION SUBSIDIARY       32789
GROUP                            27979
TOTAL EXEMPTION SMALL             9236
MEDIUM                            6079
ACCOUNTS TYPE NOT AVAILABLE       3802
AUDITED ABRIDGED                  1233
FILING EXEMPTION SUBSIDIARY        415
PARTIAL EXEMPTION                   28
INITIAL                              3
Name: count, dtype: int64

In [18]:
entity_master_v1 = entity_master.copy()

entity_master_v1 = entity_master_v1[
    (entity_master_v1["company_status"] == "Active") &
    (entity_master_v1["company_category"] == "Private Limited Company") &
    (entity_master_v1["account_category"] != "DORMANT")
].copy()

print("entity_master original shape:", entity_master.shape)
print("entity_master_v1 shape:", entity_master_v1.shape)
entity_master_v1.head()

entity_master original shape: (5677276, 17)
entity_master_v1 shape: (4191535, 17)

,entity_id,entity_name,company_category,company_status,country_of_origin,incorporation_date,account_category,sic_text_1,sic_text_2,sic_text_3,sic_text_4,post_town,county,country,postcode,source_uri,entity_name_raw
2,16873705,FE NETWORK LIMITED,Private Limited Company,Active,United Kingdom,2025-11-25,NO ACCOUNTS FILED,86210 - General medical practice activities,NaN,NaN,NaN,"HARLOW, ESSEX",NaN,UNITED KINGDOM,CM20 1YS,http://business.data.gov.uk/id/company/16873705,!FE NETWORK LIMITED
3,15073164,NFLECTION ADVISORY LIMITED,Private Limited Company,Active,United Kingdom,2023-08-15,TOTAL EXEMPTION FULL,70229 - Management consultancy activities othe...,NaN,NaN,NaN,POTTERS BAR,HERTFORDSHIRE,ENGLAND,EN6 2DA,http://business.data.gov.uk/id/company/15073164,!NFLECTION ADVISORY LIMITED
4,13522064,NFOGENIE LTD,Private Limited Company,Active,United Kingdom,2021-07-21,MICRO ENTITY,58290 - Other software publishing,NaN,NaN,NaN,LONDON,GREATER LONDON,UNITED KINGDOM,WC2H 9JQ,http://business.data.gov.uk/id/company/13522064,!NFOGENIE LTD
5,11006939,NNOV8 LIMITED,Private Limited Company,Active,United Kingdom,2017-10-11,MICRO ENTITY,62090 - Other information technology service a...,70229 - Management consultancy activities othe...,NaN,NaN,EDENBRIDGE,NaN,ENGLAND,TN8 5NF,http://business.data.gov.uk/id/company/11006939,!NNOV8 LIMITED
6,SC606050,NSPIRED INVESTMENTS LTD,Private Limited Company,Active,United Kingdom,2018-08-22,TOTAL EXEMPTION FULL,68209 - Other letting and operating of own or ...,NaN,NaN,NaN,ABERDEEN,NaN,SCOTLAND,AB11 7SY,http://business.data.gov.uk/id/company/SC606050,!NSPIRED INVESTMENTS LTD

In [19]:
# entity_master_v1["sic_text_1"].value_counts(dropna=False).head(50)

In [20]:
# exclude_patterns = [
#     "real estate",
#     "holding companies",
#     "head offices",
#     "dormant",
#     "residents property management",
# ]

# pattern = "|".join(exclude_patterns)

# entity_master_v2 = entity_master_v1[
#     ~entity_master_v1["sic_text_1"].str.lower().str.contains(pattern, na=False)
# ].copy()

# print("entity_master_v1 shape:", entity_master_v1.shape)
# print("entity_master_v2 shape:", entity_master_v2.shape)

In [21]:
# entity_master_v2["sic_text_1"].value_counts(dropna=False).head(50)

In [22]:
output_path = PROCESSED_DIR / "entity_master_v1.csv"
entity_master_v1.to_csv(output_path, index=False)
print(output_path)

/Users/lingzitong/Desktop/MSIN0166 Individual Assignment/data/processed/entity_master_v1.csv